server:
  port: 8070    # ??? ??? ?? ?? ??

spring:
  thymeleaf:
    cache: false    # ?? ???? ??? ?? ???? (??? ?? ??)
    prefix: file:src/main/resources/templates/    # ??? ?? ?? ??, file: ???? ??? ??
  output:
    ansi:
      enabled: always    # ?? ??? ANSI ?? ???

  h2:
    console:
      enabled: true     # H2 ?????? ? ?? ???
      path: /h2-console # H2 ?? ?? ?? ??

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create    # ?????? ??? ??? ?? ?? (?????)

    properties:
      hibernate:
        default_batch_fetch_size: 100  # N+1 ?? ??? ?? ?? ??? ??
        format_sql: true               # SQL ?? ???
        highlight_sql: true            # SQL ?? ?????
        use_sql_comments: true         # SQL ??? ?? ??

logging:
  level:
    org.hibernate.SQL: DEBUG                        # SQL ?? ??
    org.hibernate.orm.jdbc.bind: TRACE             # SQL ??? ???? ??
    org.hibernate.orm.jdbc.extract: TRACE          # SQL ?? ?? ??
    org.springframework.transaction.interceptor: TRACE  # ???? ??